import React from 'react';

interface Props {
  alt?: string;
  className?: string;
  sizes?: string; // e.g. "(max-width: 640px) 48px, 64px"
}

const ResponsiveLogo: React.FC<Props> = ({ alt = 'Mitché Logo', className = '', sizes }) => {
  // Serve optimized images from /optimized generated by the script
  const base = '/optimized/awardlogo';
  return (
    <picture className={className}>
      <source type="image/avif" srcSet={`${base}-64.avif 64w, ${base}-160.avif 160w, ${base}-320.avif 320w`} sizes={sizes} />
      <source type="image/webp" srcSet={`${base}-64.webp 64w, ${base}-160.webp 160w, ${base}-320.webp 320w`} sizes={sizes} />
      <img src={`${base}-160.png`} alt={alt} width={160} height={160} loading="eager" />
    </picture>
  );
};

export default ResponsiveLogo;
