name: Deploy on main

on:
  push:
    branches: [ main ]

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies (root)
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Install & build functions
        run: |
          npm --prefix functions ci
          npm --prefix functions run build

      - name: Authenticate to Google Cloud (service account)
        if: ${{ secrets.FIREBASE_SERVICE_ACCOUNT != '' && secrets.FIREBASE_PROJECT != '' }}
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      - name: Install Firebase CLI
        if: ${{ github.secrets.FIREBASE_SERVICE_ACCOUNT != '' && github.secrets.FIREBASE_PROJECT != '' }}
        run: npm install -g firebase-tools

      - name: Deploy to Firebase (hosting + functions)
        if: ${{ github.secrets.FIREBASE_SERVICE_ACCOUNT != '' && github.secrets.FIREBASE_PROJECT != '' }}
        env:
          FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT }}
        run: |
          firebase deploy --project "$FIREBASE_PROJECT" --only "hosting,functions"

      - name: Skip deploy (missing secrets)
        if: ${{ secrets.FIREBASE_SERVICE_ACCOUNT == '' || secrets.FIREBASE_PROJECT == '' }}
        run: echo "FIREBASE_SERVICE_ACCOUNT or FIREBASE_PROJECT is not set. Skipping deploy."
