name: Deploy on main (disabled auto-run)

# Automatic deploys are disabled temporarily to prevent failing automation.
# Re-enable by changing this to `on: push` after configuring OIDC/provider and secrets.
on:
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  preflight:
    name: Preflight checks
    runs-on: ubuntu-latest
    outputs:
      auth_method: ${{ steps.set-auth.outputs.auth_method }}
    steps:
      - name: Determine auth method
        id: set-auth
        run: |
          echo "Checking for OIDC provider and service account secrets..."
          if [ -n "${{ secrets.GCP_WORKLOAD_PROVIDER }}" ] && [ -n "${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}" ]; then
            echo "auth_method=oidc" >> $GITHUB_OUTPUT
          elif [ -n "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" ] && [ -n "${{ secrets.FIREBASE_PROJECT }}" ]; then
            echo "auth_method=service_account" >> $GITHUB_OUTPUT
          else
            echo "auth_method=none" >> $GITHUB_OUTPUT
          fi

      # preflight debug moved to build-and-deploy job

  build-and-deploy:
    name: Build and deploy
    needs: preflight
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Preflight debug (CI)
        run: |
          echo "=== Preflight debug (CI) ==="
          echo "Computed auth_method: ${{ needs.preflight.outputs.auth_method }}"
          if [ -n "$GCP_WORKLOAD_PROVIDER" ]; then echo "GCP_WORKLOAD_PROVIDER: set"; else echo "GCP_WORKLOAD_PROVIDER: not set"; fi
          if [ -n "$GCP_SERVICE_ACCOUNT_EMAIL" ]; then echo "GCP_SERVICE_ACCOUNT_EMAIL: set"; else echo "GCP_SERVICE_ACCOUNT_EMAIL: not set"; fi
          if [ -n "$FIREBASE_SERVICE_ACCOUNT" ]; then echo "FIREBASE_SERVICE_ACCOUNT: set"; else echo "FIREBASE_SERVICE_ACCOUNT: not set"; fi
          if [ -n "$FIREBASE_PROJECT" ]; then echo "FIREBASE_PROJECT: set"; else echo "FIREBASE_PROJECT: not set"; fi

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies (root)
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Install & build functions
        run: |
          npm --prefix functions ci
          npm --prefix functions run build

      - name: Run Lighthouse CI (gating)
        if: ${{ always() }}
        continue-on-error: true
        run: |
          echo "Building storybook (static) for visual artifacts..."
          npm run build-storybook || echo "storybook build failed (non-blocking)"
          echo "Running LHCI with .lighthouseci config (reports will be uploaded regardless of pass/fail)"
          npx lhci autorun --config ./.lighthouseci/lighthouserc.json || echo "LHCI run failed or assertions failed (non-blocking)"


      - name: Authenticate to Google Cloud (OIDC, preferred)
        id: auth
        if: ${{ needs.preflight.outputs.auth_method == 'oidc' }}
        uses: google-github-actions/auth@v1
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
      - name: Fallback - Authenticate with service account JSON (if provided)
        if: ${{ needs.preflight.outputs.auth_method == 'service_account' }}
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      - name: Install Firebase CLI
        if: ${{ needs.preflight.outputs.auth_method == 'oidc' || needs.preflight.outputs.auth_method == 'service_account' }}
        run: npm install -g firebase-tools

      - name: Upload Lighthouse reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-reports
          path: .lighthouseci

      - name: Deploy to Firebase (hosting + functions)
        if: ${{ needs.preflight.outputs.auth_method == 'oidc' || needs.preflight.outputs.auth_method == 'service_account' }}
        env:
          FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT }}
        run: |
          firebase deploy --project "$FIREBASE_PROJECT" --only "hosting,functions"

      - name: Skip deploy (missing auth or project)
        if: ${{ needs.preflight.outputs.auth_method == 'none' }}
        run: echo "No GCP auth available (workload identity or service account). Skipping deploy."
