name: E2E Client Auth Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Set service account
        if: ${{ env.FIREBASE_ADMIN_SA_B64 != '' }}
        env:
          FIREBASE_ADMIN_SA_B64: ${{ secrets.FIREBASE_ADMIN_SA_B64 }}
        run: echo "Service account provided via secret"
      - name: Run E2E client-auth test
        env:
          FIREBASE_ADMIN_SA_B64: ${{ secrets.FIREBASE_ADMIN_SA_B64 }}
        run: |
          if [ -n "$FIREBASE_ADMIN_SA_B64" ]; then
            npm run test:e2e
          else
            echo "FIREBASE_ADMIN_SA_B64 secret not set, skipping E2E client-auth test."
          fi
      - name: Upload e2e report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-report
          path: e2e-report.json
  ui-e2e:
    runs-on: ubuntu-latest
    needs: e2e
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Run Puppeteer UI E2E
        env:
          FIREBASE_ADMIN_SA_B64: ${{ secrets.FIREBASE_ADMIN_SA_B64 }}
        run: |
          if [ -n "$FIREBASE_ADMIN_SA_B64" ]; then
            node ./scripts/puppeteer-e2e.mjs
          else
            echo "FIREBASE_ADMIN_SA_B64 secret not set, skipping UI E2E test."
          fi
      - name: Upload UI report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-ui-report
          path: e2e-ui-report.json
