name: Deploy to Firebase Hosting (disabled auto-run)

# Disabled automatic triggers. Use GitHub Actions 'Run workflow' (workflow_dispatch)
# after configuring GCP OIDC provider and repository secrets.
on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build
    - name: Deploy to Firebase (script)
      run: |
        chmod +x ./scripts/deploy-hosting.sh
        ./scripts/deploy-hosting.sh
      env:
        FIREBASE_CLI_EXPERIMENTS: webframeworks